events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        # Статические файлы
        location /static/ {
            alias /usr/share/nginx/html/static/;
        }

        # HTML шаблоны (фронт будет их отдавать)
        location / {
            alias /usr/share/nginx/html/templates/meters/;
            try_files $uri $uri/ /meter_list.html;
        }

        # Прокси на Django API
        location /api/ {
            proxy_pass http://backend:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
